import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./(components)/SharedJsx/Navbar";
import { AuthProvider } from "../../AuthContext/AuthContext";
import Footer from "./(components)/SharedJsx/Footer";
// import { AuthProvider } from "../../Context/AuthContext/AuthContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
     <AuthProvider>
       <Navbar></Navbar>
        <main>
          {children}
        </main>
        <Footer/>
     </AuthProvider>
      </body>
    </html>
  );
}
